export interface TarotCard {
  id: string;
  name_en: string;
  name_vn: string;
  type: string;
  image: string;
  uprightMeaning: string;
  reversedMeaning: string;
  description: string;
  journey_story?: string;
  upright_keywords?: string[];
  reversed_keywords?: string[];
}

export const tarotDeck: TarotCard[] = [
  {
    "id": "major_0_the_fool",
    "name_en": "The Fool",
    "name_vn": "Chàng Khờ",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Fool.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Fool dự đoán sự bắt đầu của một hành trình mới trong cuộc sống, với những thách thức và cơ hội mới. Lá bài này không khẳng định sự thành công hay thất bại, mà chỉ là điềm báo về những bước nhảy trong cuộc đời.",
    "journey_story": "The Fool đại diện cho sự khởi đầu, hành trình mới và tiềm năng vô tận. Lá bài này khuyến khích bạn dấn thân vào những điều chưa biết với lòng tin và sự tò mò.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_1_the_magician",
    "name_en": "The Magician",
    "name_vn": "Ảo Thuật Gia",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Magician.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ảo Thuật Gia đại diện cho sự bắt đầu của những thách thức mới, sự sáng tạo và khả năng đạt được mục tiêu. Lá bài này nhắc nhở bạn tận dụng hết óc sáng tạo và năng lực tiềm ẩn để đạt được thành công. Trong một số tình huống, lá bài này biểu hiện cho kỹ năng và các kỹ năng của bản thân đã đến lúc phải phô diễn hết sức để đạt được thành công.",
    "journey_story": "The Magician tượng trưng cho sự sáng tạo và khả năng biến ý tưởng thành hiện thực. Lá bài này nhắc nhở bạn tận dụng nguồn lực và sức mạnh nội tại.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_2_the_high_priestess",
    "name_en": "The High Priestess",
    "name_vn": "Nữ Tư Tế",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The High Priestess.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The High Priestess là biểu tượng của sự hoài nghi cần vận dụng trực giác của bản thân để phán đoán các tình huống. Bạn sẽ có cảm giác bị che giấu bởi ai đó bên cạnh. Xét về tương lai, lá bài này dự đoán những bí mật sẽ sớm được bật mí. Lá bài khơi gợi sự tò mò trong bạn, bạn phải tĩnh tâm để bóc tách vấn đề, xem xét lại mọi sự việc để phát hiện ra những điều được ẩn giấu.",
    "journey_story": "The High Priestess đại diện cho trí tuệ nội tại và sự kết nối với tâm linh. Lá bài khuyến khích bạn lắng nghe trực giác và khám phá những bí mật trong tâm hồn.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_3_the_empress",
    "name_en": "The Empress",
    "name_vn": "Nữ Hoàng",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Empress.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Empress đại diện cho sự sinh sôi và phát triển. Lá bài này xuất hiện hình ảnh vị nữ hoàng với chiếc áo dài thụng có thể là dấu hiệu của thai kỳ, hàm ý của lá bài là mọi sự cố gắng của bạn như đứa con trong bụng mẹ đã đến ngày đạt được trái ngọt. Lá bài cũng có thể là dấu hiệu của một người phụ nữ trong gia đình bạn có thể là mẹ, chị gái, em gái hoặc chính bạn đang có những tin vui về tình yêu.",
    "journey_story": "The Empress là biểu tượng của sự phong phú, tình yêu và sự nuôi dưỡng. Lá bài này nhắc nhở bạn kết nối với thiên nhiên và năng lượng sáng tạo.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_4_the_emperor",
    "name_en": "The Emperor",
    "name_vn": "Hoàng Đế",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Emperor.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Emperor tượng trưng cho sức mạnh và quyền lực. Hình ảnh trên lá bài là một vị vua với quyền lực đầy mình, một tay nắm lấy vương trượng, ngôi vương được trang trí những hình thù đại diện cho cung Bạch Dương. Ý nghĩa của The Emperor bao hàm cả sự tích cực và tiêu cực, thể hiện ở việc bạn đang có sức mạnh và sự giúp đỡ của những người có quyền lực, bạn có một tham vọng lớn trong sự nghiệp điều này sẽ thúc đẩy sự phát triển của bạn.",
    "journey_story": "The Emperor đại diện cho quyền lực, sự ổn định và trật tự. Lá bài khuyến khích bạn sử dụng trí tuệ và kỷ luật để xây dựng nền tảng vững chắc.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_5_the_hierophant",
    "name_en": "The Hierophant",
    "name_vn": "Giáo Hoàng",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Hierophant.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Hierophant mang đến những giá trị về tinh thần và sự học hỏi. Lá bài đưa ra dự đoán bạn sẽ gặp được người cố vấn, người thầy mang lại cho bạn những bài học trong cuộc sống. Người dẫn đường này có thể khá nghiêm túc, khó tính nhưng sâu bên trong là những bài học về tình cảm và đạo đức.",
    "journey_story": "The Hierophant biểu thị sự truyền thống, giáo dục và sự hướng dẫn. Lá bài khuyến khích bạn học hỏi từ các bậc thầy và tuân theo những giá trị lâu đời.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_6_the_lovers",
    "name_en": "The Lovers",
    "name_vn": "Tình Nhân",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Lovers.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Lovers đại diện cho những đam mê trong tình yêu và các mối quan hệ. Lá bài này đánh dấu một mối quan hệ khiến bạn hứng thú và chìm sâu, chiếm hầu hết thời gian của bạn. Tuy nhiên, mọi đam mê khi đẩy đến cao trào sẽ phản tác dụng khiến mối quan hệ xuất hiện những tiêu cực.",
    "journey_story": "The Lovers đại diện cho sự kết nối sâu sắc, tình yêu và sự lựa chọn có ý nghĩa. Lá bài nhắc nhở bạn rằng mọi quyết định đều có tác động đến con đường phía trước.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_7_the_chariot",
    "name_en": "The Chariot",
    "name_vn": "Cỗ Xe",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Chariot.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Chariot tượng trưng cho sự chiến thắng, vinh quang và thành công. Nó dự báo bạn sẽ thắng áp đảo đối thủ nhanh chóng và mọi thành công trong công việc, tình yêu cũng sẽ xuất hiện sớm nhất có thể. Lá bài này như một liều thuốc tinh thần động viên bạn hãy cố gắng hơn nữa để nếm trái ngọt. Tuy nhiên, lá bài cũng khuyên bạn nên cẩn trọng trong lời nói và hành động để tránh thị phi không đáng có và nên khiêm tốn để nhận được sự kính trọng và ngưỡng mộ từ mọi người.",
    "journey_story": "The Chariot biểu thị sự quyết tâm, ý chí mạnh mẽ và khả năng kiểm soát để đạt được chiến thắng. Lá bài này khuyến khích bạn điều hướng qua những thử thách với sự tự tin.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_8_strength",
    "name_en": "Strength",
    "name_vn": "Sức Mạnh",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/Strength.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Strength đại diện cho sức mạnh tiềm tàng của mỗi con người. Khi lá bài này đến với bạn, nghĩa là sức mạnh tiềm ẩn sâu bên trong bạn sẽ là vũ khí sắc bén để vượt qua những thử thách trong công việc, tình yêu đôi lứa và mối quan hệ xã hội. Lá bài nhắc nhở bạn kiểm tra lại tình hình sức khỏe, tuân theo một thực đơn ăn uống lành mạnh và sử dụng thức uống thanh lọc cơ thể.",
    "journey_story": "Strength biểu thị lòng can đảm, sự dịu dàng và sức mạnh nội tại. Lá bài nhắc nhở rằng bạn có thể vượt qua thử thách bằng lòng trắc ẩn và kiên nhẫn.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_9_the_hermit",
    "name_en": "The Hermit",
    "name_vn": "Ẩn Sĩ",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Hermit.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Hermit tượng trưng cho sự cô độc, lạc lõng và cần không gian riêng tư để suy nghĩ về bản thân. Đây là giai đoạn của sự cô đơn về tâm hồn, và có thể là dấu hiệu của sự rạn nứt trong mối quan hệ tình cảm hoặc sự thiếu tinh tế của người khác. Lá bài này cũng thể hiện sự cần thiết của việc tìm kiếm câu trả lời từ bên trong và biết rằng câu trả lời chỉ đến từ sự tĩnh lặng và cô độc.",
    "journey_story": "The Hermit đại diện cho sự cô lập để chiêm nghiệm và khám phá bản thân. Lá bài này nhắc nhở bạn cần thời gian yên tĩnh để tập trung vào mục tiêu thực sự của mình.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_10_wheel_of_fortune",
    "name_en": "Wheel of Fortune",
    "name_vn": "Bánh Xe Số Phận",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/Wheel Of Fortune.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Wheel of Fortune đại diện cho bước chuyển khó nhận diện trong cuộc đời một người. Nó là hình ảnh ẩn dụ cho vòng tròn tổng thể lớn hơn, nơi mà vận mệnh của mọi đàn ông và phụ nữ đan xen vào nhau tạo thành tấm thảm cuộc sống. Mỗi người sẽ tự chọn con đường cho mình, nhưng vẫn nằm trong một vòng tròn tổng thể lớn hơn.",
    "journey_story": "Wheel of Fortune biểu thị sự thay đổi, vận mệnh và chu kỳ của cuộc sống. Lá bài này nhắc nhở rằng mọi thứ đều có lúc thăng trầm, và sự linh hoạt là cần thiết.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_11_justice",
    "name_en": "Justice",
    "name_vn": "Công Lý",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/Justice.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Justice đại diện cho sự công bằng, pháp luật và sự công lý. Nó thường xuất hiện khi bạn đang gặp phải những vấn đề liên quan đến pháp luật, quan hệ tình cảm hoặc công việc. Lá bài này cũng có thể cho thấy rằng bạn đang phải đối mặt với những hậu quả của những hành động trước đây của mình.",
    "journey_story": "Justice biểu thị sự công bằng, trung thực và trách nhiệm. Lá bài nhắc nhở rằng mọi hành động đều có hậu quả, và sự thật sẽ được phơi bày.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_12_the_hanged_man",
    "name_en": "The Hanged Man",
    "name_vn": "Người Treo Ngược",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Hanged Man.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Hanged Man là một lá bài bí ẩn, khẳng định rằng bạn phải buông bỏ một thứ gì đó đang bên cạnh bạn nếu muốn nhận lại thứ lớn hơn. Đôi khi bạn phải bỏ ra tiền bạc, thời gian, sức khỏe hoặc thứ gì đó bạn yêu thích. Bạn bắt buộc phải trải qua cảm giác hụt hẫng và buồn rầu khi phải từ bỏ để hướng đến mục tiêu cao hơn. Đôi khi, lá bài đại diện cho sự vượt qua bệnh tật của bạn, nghị lực, tiền bạc, thời gian để chữa chị là thứ bạn phải mất để lấy lại trạng thái cân bằng.",
    "journey_story": "The Hanged Man biểu thị sự tạm dừng, hy sinh và thay đổi quan điểm. Lá bài nhắc nhở rằng đôi khi cần phải buông bỏ để đạt được sự sáng suốt.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_13_death",
    "name_en": "Death",
    "name_vn": "Cái Chết",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/Death.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Death đại diện cho sự kết thúc trong cuộc sống, tình yêu và sự nghiệp của bạn. Nó thường khiến nhiều người lo lắng khi nó có nghĩa là cái chết, nhưng ý nghĩa ẩn dấu sâu bên trong lại là những ý nghĩa tích cực. Lá bài này mang đến một kết thúc có nhiều phần đau đớn nhưng cần thiết, và bạn phải trải qua những thay đổi lớn trong cuộc đời để trở nên mạnh mẽ hơn. Death còn dự báo cái chết và sự mất mát, nhưng khi nhìn lại, bạn phải chấp nhận nó để hướng đến cuộc sống tương lai.",
    "journey_story": "Death không biểu thị cái chết vật lý mà là sự kết thúc, chuyển đổi và tái sinh. Lá bài nhắc nhở rằng sự kết thúc mở ra cơ hội cho một khởi đầu mới.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_14_temperance",
    "name_en": "Temperance",
    "name_vn": "Cân Bằng",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/Temperance.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Temperance mang ý nghĩa sự cân bằng trong cuộc sống. Bạn sẽ sớm lấy lại trạng thái cân bằng với các mối quan hệ và vấn đề trong cuộc sống. Bạn thỏa mãn với cuộc sống hiện tại, bạn hài lòng với những gì mình có. Đây là một tín hiệu tốt vì lòng tham con người vô đáy, hài lòng cũng là một trạng thái hạnh phúc.",
    "journey_story": "Temperance biểu thị sự cân bằng, điều độ và hài hòa. Lá bài nhắc nhở bạn cần giữ vững sự điều chỉnh trong các khía cạnh khác nhau của cuộc sống.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_15_the_devil",
    "name_en": "The Devil",
    "name_vn": "Ác Quỷ",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Devil.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ác Quỷ thể hiện cho những ước muốn của con người. Khi lá bài được lật lên có nghĩa là tình yêu, công việc của bạn sẽ xoay chuyển theo một tình huống nhất định, có thể tốt lên hoặc xấu đi. Nhưng tin buồn là trường hợp xấu đi thường xảy ra nhiều hơn cả. Lá bài cảnh báo rằng những gì bạn đang dốc hết sức đeo bám sẽ chẳng mang lại gì ngoài sự thất vọng và chán nản. Tuy vậy, bạn vẫn không thoát được vòng tròn luẩn quẩn đó, bạn vẫn cố đi theo con đường cũ và ngày càng lấn sâu. Nhưng đôi khi ý nghĩa lá bài The Devil cũng mang lại những điều tích cực. Lá bài khuyên bạn nên mạnh mẽ và hành động dứt khoát. Đôi khi bạn buộc phải gạt tình cảm sang một bên, đấu tranh không khoan nhượng với người khác để dành chiến thắng. Bạn sở hữu một lý tưởng và tham vọng đủ lớn để thực hiện điều đó.",
    "journey_story": "The Devil biểu thị sự ràng buộc, cám dỗ và những khía cạnh tối trong tâm hồn. Lá bài nhắc nhở bạn cần nhận thức và vượt qua những điều tiêu cực để giải thoát bản thân.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_16_the_tower",
    "name_en": "The Tower",
    "name_vn": "Tòa Tháp",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Tower.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Tòa Tháp đại diện cho sự sụp đổ, thử thách và thay đổi. Nó ám chỉ sự dằn vặt, trống rỗng trong cuộc sống thực tại và cần có sự thay đổi bản thân để đón nhận nhiều may mắn hơn. Lá bài này cũng mang ý nghĩa tích cực, thông điệp là cơn bão trong cuộc sống đang qua đi, bạn sẽ sống với tinh thần mạnh mẽ, lạc quan hơn.",
    "journey_story": "The Tower biểu thị sự thay đổi đột ngột, sự phá vỡ và sự sụp đổ của những nền tảng không ổn định. Lá bài nhắc nhở rằng đôi khi những thay đổi đau đớn là cần thiết để tái thiết.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_17_the_star",
    "name_en": "The Star",
    "name_vn": "Ngôi Sao",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Star.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Star mang đến hy vọng và dự báo rằng ước mơ và mong muốn của bạn sắp thành hiện thực. Lá bài này nói rằng bạn rất có triển vọng và tổ chất của một người thành công, bạn có một trí tuệ thông thái để phân biệt mọi chuyện. Tuy nhiên, lá bài cũng cảnh báo bạn đang thể hiện bản thân và tỏa sáng như một ngôi sao quá nhiều, điều này khiến bạn trở thành cái gai trong mắt một số người, điều này sẽ mang đến những thị phi. Về tình yêu, tương lai về một tình yêu hứa hẹn nhiều thú vị đang đến gầy. Về công việc, bạn thật may mắn khi nhận được lá bài The Star, vì ý nghĩa luôn đem lại tín hiệu tích cực trong bài đọc về công việc. Đừng bỏ cuộc vì mọi cố gắng sẽ được đền bù xứng đáng sớm thôi.",
    "journey_story": "The Star biểu thị hy vọng, cảm hứng và sự dẫn đường của ánh sáng trong những thời điểm khó khăn. Lá bài khuyến khích bạn tin tưởng vào khả năng của mình và nhìn về phía trước.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_18_the_moon",
    "name_en": "The Moon",
    "name_vn": "Mặt Trăng",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Moon.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Mặt Trăng thường mang hàm ý lừa dối. Đôi khi, lá bài ám chỉ những bí mật của bạn hoặc những người xung quanh có ảnh hưởng đến bạn đang được giấu kín. Mặt khác, lá bài cũng có thể đại diện cho sự lừa dối. Sự dối trá đó có thể xuất phát từ những người xa lạ đến thân cận nhất của bạn, cũng có thể bạn đang đánh lừa họ. The Moon thường mang tính chu kỳ, tâm trạng của bạn có thể thay đổi liên tục trong thời gian tới.",
    "journey_story": "The Moon biểu thị sự bí ẩn, ảo tưởng và những nỗi sợ tiềm ẩn. Lá bài nhắc nhở rằng không phải tất cả mọi thứ đều như vẻ bề ngoài và cần trực giác để khám phá sự thật.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_19_the_sun",
    "name_en": "The Sun",
    "name_vn": "Mặt Trời",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The Sun.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The Sun đại diện cho mặt trời, mang đến ánh sáng, niềm vui cho cuộc sống và các dự định trong tương lai. Nó dự báo một kết quả tốt đối với công việc và các mối quan hệ, bạn có thể yên tâm với những việc mình đang làm vì chúng sẽ sớm đạt được thành công như mong đợi. The Sun thường xuất hiện với ý nghĩa tích cực nhưng đôi khi nó cũng xuất hiện dưới dạng tiêu cực. Bạn không thỏa mãn với những gì mình có. Bạn có thể sẽ chỉ nhìn thấy những mặt tốt trong các mối quan hệ mà không thấy được những mặt xấu ẩn nấp.",
    "journey_story": "The Sun biểu thị niềm vui, thành công và sự rõ ràng. Lá bài nhắc nhở bạn tận hưởng thành quả và cảm nhận ánh sáng tích cực trong cuộc sống.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_20_judgement",
    "name_en": "Judgement",
    "name_vn": "Phán Xét",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/Judgement.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Judgement là một trong những lá bài quan trọng nhất trong bộ Tarot. Nó đại diện cho sự thay đổi lớn, kết quả của nỗ lực và quyết định của bạn. Judgement thường xuất hiện khi cuộc đời có những cột mốc thay đổi lớn, như sự chuyển tiếp trong mối quan hệ tình cảm, sự khởi đầu của công việc sau những ngày tháng đầy gian nan. Lá bài này mang đến những phán quyết cho các vấn đề và mối quan hệ trong cuộc sống, giúp bạn nhận thức rõ ràng về vị trí thực tế mình đang đứng và xác định mình cần làm gì để thành công.",
    "journey_story": "Judgement biểu thị sự thức tỉnh, sự phán xét và thay đổi lớn trong cuộc đời. Lá bài nhắc nhở bạn đánh giá lại hành động của mình và sẵn sàng thay đổi.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "major_21_the_world",
    "name_en": "The World",
    "name_vn": "Thế Giới",
    "type": "Major Arcana",
    "image": "/images/tarot_vn/The World.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài The World mở ra một tương lai tích cực. Đây là lá bài của sự trọn vẹn, khi lá bài xuất hiện có nghĩa là bạn đang ở điểm cuối cùng của chặng đường và sắp bước sang một giai đoạn mới. The World thể hiện những tham vọng và mơ ước của cuộc đời đã thành hiện thực. Những thành quả tạo dựng của bản thân đang vào nề nếp và bạn có thể thả lỏng đôi chút. Đôi khi lá bài đại diện cho sự di chuyển, bạn có thể sẽ di cư hoặc du lịch tới một thành phố hoặc đất nước mới trong giai đoạn tới. Điều đáng mừng là ý nghĩa lá bài The World hiếm khi mang thông điệp tiêu cực. Nếu xuất hiện dưới dạng tiêu cực, The World an ủi rằng hãy cố gắng rồi bạn sẽ sớm bước lên bục vinh quang. Bên cạnh đó, sẽ có trường hợp lá bài dự đoán một khởi đầu mới trong cuộc sống hoặc mối quan hệ, nhưng sự thay đổi này chưa hẳn đã là điều bạn mong muốn.",
    "journey_story": "The World biểu thị sự hoàn thành, thành tựu và chu kỳ khép lại. Lá bài nhắc nhở bạn rằng mọi nỗ lực đã được đền đáp và một hành trình mới đang chờ đợi.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_ace",
    "name_en": "Ace of Wands",
    "name_vn": "Ace of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ace Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Ace of Wands là lá bài mang thông điệp của sự sáng tạo. Khi lá bài này xuất hiện trong bài đọc, bạn có thể an tâm vì những thứ bạn đang thực hiện sẽ có tác động và đột phá. Ace of Wands thiên nhiều về công việc, lá bài ám chỉ những sự bứt phá trong công việc, những ý tưởng của bạn sẽ mang lại giá trị. Lá bài này cũng ẩn chứa đam mê, đôi khi là sự phát sinh một sở thích mới. Mặt khác, lá bài này thông báo một khởi đầu mới đầy thú vị. Bạn hồi hộp trải nghiệm những thứ bạn đam mê, sự thú vị và phấn khích khiến bạn đầy hứng thú tìm hiểu chúng. Nhưng đôi khi sự thú vị này biến mất, bạn rơi vào trạng thái khó khăn để tiếp tục với những thú vui này. Bạn có thể phải làm đi làm lại nhiều lần nhưng hầu như không có kết quả gì.",
    "journey_story": "Ace of Wands biểu thị sự khởi đầu của năng lượng sáng tạo, nhiệt huyết và cơ hội mới. Lá bài nhắc nhở bạn nắm bắt những ý tưởng mới và dám hành động.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_two",
    "name_en": "Two of Wands",
    "name_vn": "Two of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Two Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Two of Wands thường đại diện cho sự hợp tác và thành tích tốt. Lá bài này ám chỉ bạn sẽ nhận được nhiều sự ủng hộ và giúp đỡ của những người xung quanh. Tuy nhiên, nó cũng có thể xuất hiện dưới dạng tiêu cực, khi bạn đạt được mục tiêu nhưng không thỏa mãn. Tất cả các ước muốn của bạn sẽ không còn nhiều giá trị khi bạn đạt được chúng.",
    "journey_story": "Two of Wands biểu thị sự lập kế hoạch, tầm nhìn dài hạn và sự cân nhắc giữa các lựa chọn. Lá bài nhắc nhở bạn hãy dũng cảm theo đuổi mục tiêu của mình.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_three",
    "name_en": "Three of Wands",
    "name_vn": "Three of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Three of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Three of Wands đại diện cho sự thỏa mãn thành công, cơ hội và sự hợp tác. Lá bài này cho thấy thời điểm này các cơ hội sẽ lần lượt đến, một nơi ở mới hoặc ý tưởng mới sẽ tạo ra hiệu quả hơn con đường cũ bạn vẫn đi. Để thành công, bạn phải nắm lấy cơ hội này và hoàn thành nhiệm vụ dù đối tượng cộng tác có đem lại cảm giác dễ chịu hay không.",
    "journey_story": "Three of Wands biểu thị sự mở rộng, chờ đợi kết quả và tìm kiếm cơ hội mới. Lá bài nhắc nhở bạn hãy kiên nhẫn và sẵn sàng để đón nhận thành công.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_four",
    "name_en": "Four of Wands",
    "name_vn": "Four of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Four Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Four of Wands mang đến sự ổn định và hòa hợp trong cuộc sống. Khi lá bài xuất hiện, mọi vấn đề trong cuộc sống đang hoặc sắp đi vào quỹ đạo. Đây là lá bài trấn an các vấn đề về gia đình, mọi xung đột sẽ sớm được giải quyết. Four of Wands là lá bài của gia đình, thông điệp nó mang tới là đừng lo lắng, căng thẳng mọi chuyện sẽ có kết thúc tốt đẹp, gia đình của bạn sẽ hạnh phúc trở lại. Lá bài còn biểu thị cơ hội của bạn qua tầm nhìn của người đàn ông trong lá bài. Những cơ hội tốt sẽ đến, hãy giữ tâm lý thoải mái để đón nhận. Đôi khi bạn phải thay đổi bản thân để nắm bắt cơ hội và thoát ra khỏi vùng an toàn. Mặc khác, lá bài Three of Wands xuôi báo hiệu một chuyến du lịch đang được ấp ủ. Bạn nên có một vài chuyến đi xa để mở mang đầu óc, tầm nhìn, cơ hội có thể xuất hiện ngay trong chuyến đi đó.",
    "journey_story": "Four of Wands biểu thị sự ổn định, lễ kỷ niệm và sự hài hòa. Lá bài nhắc nhở bạn trân trọng những khoảnh khắc đáng nhớ và cảm nhận niềm vui từ sự ổn định.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_five",
    "name_en": "Five of Wands",
    "name_vn": "Five of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Five Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Five of Wands dự đoán bạn sắp trải qua một cuộc thi hoặc cạnh tranh với một đối thủ nào đó trong thời gian tới. Đôi khi, lá bài dự đoán đây sẽ là sự cạnh tranh thân thiện, giúp bạn hoàn thiện và tiến về phía trước. Nhưng lâu dần những tranh đua này có thể sẽ nảy sinh mâu thuẫn. Sự cạnh tranh đang đến gần, tuy nó không gay gắt vào thời điểm này nhưng sự cạnh tranh sẽ sớm đi đến xung đột. Ai đó sẽ trở nên ghen tỵ và có ý đồ muốn hạ bệ sự uy tín của bạn. Bạn đang mất thời gian với việc quan sát những việc người khác làm gì và nảy sinh đố kỵ thay vì làm tốt nhiệm vụ của mình. Thay vì vậy, nếu tận dụng sự đố kỵ và tham vọng của mình đúng chỗ  bạn sẽ sớm đạt được điều mình mong muốn.",
    "journey_story": "Five of Wands biểu thị sự cạnh tranh, mâu thuẫn và xung đột. Lá bài nhắc nhở bạn học cách làm việc cùng nhau và vượt qua những khác biệt.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_six",
    "name_en": "Six of Wands",
    "name_vn": "Six of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Six Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Six of Wands dự đoán sự thành công trong hiện tại và tương lai, những nỗ lực cá nhân sẽ được đền đáp xứng đáng. Lá bài Six of Wands tượng trưng cho sự công nhận những cống hiến cho công việc. Nỗ lực bỏ ra sẽ được phần thưởng tương xứng, đây là giai đoạn của sự tận hưởng.",
    "journey_story": "Six of Wands biểu thị sự chiến thắng, sự công nhận và cảm giác tự hào. Lá bài nhắc nhở bạn trân trọng thành công của mình và tiếp tục tiến lên.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_seven",
    "name_en": "Seven of Wands",
    "name_vn": "Seven of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Seven Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Seven of Wands đại diện cho sự chiến đấu và thách thức. Nó cho thấy bạn đang phải đối mặt với những khó khăn và thử thách trong cuộc sống, công việc hoặc tình yêu. Bạn cần phải chuẩn bị tinh thần và vũ khí để đối mặt với những thách thức này và giành lại quyền lợi và công bằng cho chính mình.",
    "journey_story": "Seven of Wands biểu thị sự bảo vệ, lập trường vững chắc và vượt qua thử thách. Lá bài nhắc nhở bạn giữ vững quan điểm và tiếp tục chiến đấu cho những gì bạn tin tưởng.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_eight",
    "name_en": "Eight of Wands",
    "name_vn": "Eight of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Eight Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Eight of Wands đại diện cho sự trao đổi thông tin, giao tiếp với xã hội nhiều hơn. Nó ám chỉ sự giao tiếp của bạn với cộng đồng có thể mang lại cơ hội tốt, bao gồm cả cơ hội kinh doanh và mối quan hệ. Lá bài còn đại diện cho những thứ đang được hình thành và phát triển nhanh, có thể là tiến triển của công việc hoặc một mối quan hệ cá nhân. Tuy nhiên, nó cũng có thể ám chỉ sự áp đảo và chứng nghiện mạng xã hội. Về tình yêu, lá bài mang đến tín hiệu tốt đối với các lời tỏ tình và cầu hôn. Về công việc, lá bài cho thấy giai đoạn thuận lợi trong sự nghiệp, mọi tình huống phát sinh đều được giải quyết êm đẹp. Về tiền bạc, những mối lo về khó khăn về tiền bạc và các khoản nợ sẽ sớm được giải quyết.",
    "journey_story": "Eight of Wands biểu thị sự chuyển động, tiến triển nhanh chóng và những sự kiện bất ngờ. Lá bài nhắc nhở bạn hãy sẵn sàng nắm bắt cơ hội khi chúng đến.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_nine",
    "name_en": "Nine of Wands",
    "name_vn": "Nine of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Nine Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Nine of Wands ám chỉ sự từ bỏ, thất bại và bế tắc. Nó có thể đánh dấu những khó khăn và thất bại nhỏ tích lũy và đè nặng lên vai. Tuy nhiên, nó cũng có thể là dấu hiệu tốt, nhắc nhở bạn rằng sự từ bỏ có thể là lựa chọn tốt nhất trong một số trường hợp.",
    "journey_story": "Nine of Wands biểu thị sự kiên cường, chuẩn bị và bảo vệ. Lá bài nhắc nhở bạn không từ bỏ dù đã trải qua nhiều thử thách.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_ten",
    "name_en": "Ten of Wands",
    "name_vn": "Ten of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ten Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ten of Wands ám chỉ sự chăm chỉ và nỗ lực. Khi lá bài xuất hiện, bạn sẽ có rất nhiều việc phải làm và phải cố gắng gấp nhiều lần hiện tại để đạt được mục tiêu. Những thử thách sắp tới sẽ vô cùng gian nan và khó khăn, đòi hỏi một nghị lực cùng sự cố gắng thật nhiều. Bạn sẽ cảm thấy choáng ngợp trước những khó khăn dồn dập tới cùng một lúc. Tuy nhiên, lá bài cũng dự báo khối lượng công việc và áp lực quá lớn sẽ khiến bạn chán nản, suy kiệt. Để thành công, bạn cần phải tập trung vào mục tiêu chính, tránh tham lam ôm quá nhiều việc mà không giải quyết cùng một lúc được. Hãy cố gắng gấp hai, gấp ba lần hiện tại bạn sẽ nhìn thấy con đường dẫn tới thành công.",
    "journey_story": "Ten of Wands biểu thị sự áp lực, trách nhiệm và gánh nặng. Lá bài nhắc nhở bạn hãy học cách chia sẻ trách nhiệm và không tự làm mọi thứ một mình.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_page",
    "name_en": "Page of Wands",
    "name_vn": "Page of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Page Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Page of Wands đại diện cho sự tò mò và ham muốn khám phá học hỏi của bạn trong thời gian sắp tới. Bạn sẽ rất hào hứng với nhiệm vụ được giao, bạn coi chúng là những cơ hội mới mẻ đem lại cảm giác thú vị. Bạn gần như sẽ tận hưởng chúng mà không biết rằng mọi nhiệm vụ đều ẩn chứa những thử thách. Tổng quan về lá bài Page of Wands, lá bài này tượng trưng cho tinh thần ham học hỏi cùng sự sáng tạo. Bạn coi những vấn đề trước mắt là cơ hội được học hỏi, trau dồi. Bạn nghĩ ra rất nhiều ý tưởng hay ho nhưng lại thiếu tự tin để thực hiện. Đôi khi, lá bài mang nghĩa tiêu cực, bạn khá hứng thú với công việc hoặc nhiệm vụ mới nhưng lại nhanh chóng chán nản và bỏ dở giữa chừng. Nếu vấn đề trở nên rắc rối, thử thách trở nên khắc nghiệt bạn sẽ muốn rũ bỏ chúng.",
    "journey_story": "Page of Wands biểu thị sự sáng tạo, sự tò mò và tinh thần khám phá. Lá bài nhắc nhở bạn hãy dám thử nghiệm và khám phá những ý tưởng mới.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_knight",
    "name_en": "Knight of Wands",
    "name_vn": "Knight of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Knight Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Knight of Wands đại diện cho hành động nhanh chóng, sự vội vàng và tốc độ. Nó dự báo sự thay đổi nhanh chóng trong cuộc sống, có thể là một mối quan hệ mới, một cơ hội mới hoặc một thay đổi trong công việc. Lá bài này cũng ám chỉ sự độc lập, tự do và sự sẵn sàng để theo đuổi giấc mơ của mình.",
    "journey_story": "Knight of Wands biểu thị sự nhiệ t huyết, quyết đoán và tinh thần phiêu lưu. Lá bài nhắc nhở bạn hãy hành động với sự đam mê và lòng dũng cảm.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_queen",
    "name_en": "Queen of Wands",
    "name_vn": "Queen of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Queen Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Queen of Wands đại diện cho nữ hoàng quyền lực, tham vọng. Người phụ nữ đang mang tham vọng đạt đến đỉnh cao trong sự nghiệp hoặc làm chủ thế giới của mình. Lá bài ám chỉ những người sống thiên về cảm giác, thông minh và có khả năng lãnh đạo. Khi lá bài xuất hiện có nghĩa bạn đang trên đỉnh cao của sự ham muốn chinh phục thử thách. Bạn đang sở hữu năng lượng dồi dào, bạn khao khát chinh phục các thử thách. Bạn luôn cố gắng cân bằng cảm xúc của mình, trước khi đưa ra bất kỳ phán xét hay quyết định nào bạn đều có sự ngẫm nghĩ kỹ lưỡng. Bạn đang duy trì một lối sống lành mạnh, có ý thức với việc giữ gìn vóc dáng và sức khỏe. Điều này giúp bạn trở thành người hoàn hảo toàn diện, bạn đang thay đổi theo hướng tích cực. Tuy nhiên, lá bài đưa ra cảnh cáo về việc bạn đang quá tham vọng và độc đoán. Bạn cố gắng kiểm soát mọi thứ, gây ra áp lực cho mọi người xung quanh và chính bản thân mình.",
    "journey_story": "Queen of Wands đại diện cho sự tự tin, sáng tạo và niềm đam mê. Lá bài nhắc nhở bạn hãy thể hiện bản thân một cách mạnh mẽ và đầy cảm hứng.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_wands_king",
    "name_en": "King of Wands",
    "name_vn": "King of Wands",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/King Of Wands.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài King of Wands đại diện cho người đàn ông quyền lực, giàu có và uy nghiêm. Nó thể hiện sự sáng tạo và thông minh nơi bạn, bạn có nhiều ý tưởng hay ho cho công việc và sở hữu những sức mạnh có thể xoay chuyển các tình huống. Bạn rất chắc chắn vào niềm tin của mình và sẽ tranh đấu đến cùng để bảo vệ nó. Tuy nhiên, lá bài cũng thể hiện sự độc đoán và chuyên quyền trong cách làm việc của bạn.",
    "journey_story": "King of Wands biểu thị sự lãnh đạo, tầm nhìn xa và khả năng truyền cảm hứng. Lá bài nhắc nhở bạn hãy sử dụng sức mạnh của mình để dẫn dắt và hỗ trợ người khác.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_ace",
    "name_en": "Ace of Cups",
    "name_vn": "Ace of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ace Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ace of Cups đại diện cho sự khởi đầu của tình yêu, tình yêu xuất hiện trong lá bài là thứ tình cảm trong sáng thuần khiết. Lá bài thường xuất hiện khi bạn muốn bắt đầu một mối quan hệ tình cảm. Giai đoạn này cuộc sống của bạn sẽ có nhiều tình yêu thương và hạnh phúc cùng sự thỏa mãn.",
    "journey_story": "Ace of Cups biểu thị sự khởi đầu của cảm xúc, tình yêu và lòng từ bi. Lá bài này là biểu tượng của sự tuôn trào cảm xúc và khả năng kết nối với trái tim.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_two",
    "name_en": "Two of Cups",
    "name_vn": "Two of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Two Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Two of Cups dự đoán về sự khởi đầu và tình yêu đích thực. Nó báo hiệu mối quan hệ tình cảm trong thời gian tới sẽ khá ngọt ngào và hạnh phúc. Nếu bạn đang mất niềm tin vào tình yêu thì lá bài chính là tia hy vọng bạn nên nắm giữ. Lá bài dự đoán sự hợp tác, đó có thể là sự hợp tác trong mối quan hệ tình cảm hoặc trong công việc. Thời gian này, sẽ có một người quan trọng xuất hiện, người này sẽ có ảnh hưởng tích cực với bạn và mong muốn của họ là được cộng tác cùng bạn. Lá bài thường là dấu hiệu của tình yêu đôi lứa, bạn có thể gặp được một nửa của mình trong thời gian này. Tuy nhiên, lá bài cũng có thể xuất hiện dưới dạng tiêu cực, khi bạn đang quá mềm lòng và cảm thông với nỗi đau của người khác, bạn sẵn sàng để họ bước vào cuộc sống của mình.",
    "journey_story": "Two of Cups đại diện cho sự hòa hợp, đối tác và kết nối. Lá bài biểu thị mối quan hệ cân bằng, đôi bên cùng có lợi và sự tôn trọng lẫn nhau.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_three",
    "name_en": "Three of Cups",
    "name_vn": "Three of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Three Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Three of Cups thể hiện sự vui vẻ và tận hưởng. Lá bài mang đến tin vui, một buổi tiệc ăn mừng chiến thắng có thể sẽ diễn ra. Lá bài thể hiện sự thành công và thăng hoa, mọi điều tốt đẹp sẽ đến trong lá bài Three of Cups. Nếu bạn đang bị mắc kẹt trong nợ nần hoặc áp lực thì giai đoạn này mọi vấn đề sẽ được giải quyết.",
    "journey_story": "Three of Cups biểu thị sự kỷ niệm, tình bạn và niềm vui chung. Lá bài này nhắc nhở bạn tận hưởng những khoảnh khắc hạnh phúc và trân trọng sự kết nối với người khác.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_four",
    "name_en": "Four of Cups",
    "name_vn": "Four of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Four Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Four of Cups đại diện cho sự chán nản, nhàm chán và bế tắc trong cuộc đời. Nó dự báo rằng bạn sẽ không có bất kỳ sự hài lòng nào xảy ra khi không có hành động để thay đổi. Công việc kinh doanh sẽ gặp rắc rối hoặc trì hoãn dẫn đến thâm hụt lợi nhuận hoặc các mối quan hệ đang dần mất thú vị.",
    "journey_story": "Four of Cups biểu thị sự suy tư, kh ông hài lòng hoặc bỏ qua cơ hội. Lá bài nhắc nhở bạn chú ý đến những cơ hội mới đang đến gần.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_five",
    "name_en": "Five of Cups",
    "name_vn": "Five of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Five Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Five of Cups tượng trưng cho sự thất vọng, bạn sẽ cảm thấy mình đang ở giai đoạn bất lực với mọi thứ. Lá bài Five of Cup thường xuất hiện khi chấm dứt mối hệ tình cảm. Bạn đang chìm đắm trong quá khứ và hối tiếc những kỉ niệm cũ, sự day dứt và dằn vặt khiến bạn mất toàn bộ động lực để làm lại từ đầu. Đôi khi lá bài có nghĩa tích cực hơn, những sai lầm trong quá khứ sẽ là bài học quý giá cho sau này.",
    "journey_story": "Five of Cups biểu thị sự mất mát, tiếc nuối và tập trung vào những điều đã mất. Lá bài nhắc nhở bạn rằng vẫn còn cơ hội và hy vọng phía trước.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_six",
    "name_en": "Six of Cups",
    "name_vn": "Six of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Six Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Six of Cups đại diện cho hồi ức, thời điểm này một điều đó từ quá khứ có thể trở lại. Điều này có thể là những ký ức tuổi thơ hạnh phúc sẽ quay trở lại hoặc bạn sẽ gặp lại người thân cũ sau nhiều tháng ngày xa cách. Đây là một lá bài tốt khi nói về gia đình và sự hạnh phúc trong các mối quan hệ tình cảm. Mặc dù những điều ở quá khứ khiến bạn hạnh phúc và muốn trải nghiệm lại nhưng không phải tất cả chúng đều tốt, sẽ có cả ký ức xấu quay lại ám ảnh bạn. Lá bài đánh dấu giai đoạn bạn lạc mất những thứ mình trân quý, sự mất mát này không đến từ những việc bạn đã làm mà đến từ những thứ bạn chưa làm.",
    "journey_story": "Six of Cups đại diện cho ký ức tuổi thơ, sự hoài niệm và lòng tốt. Lá bài này nhắc nhở bạn về giá trị của việc kết nối với quá khứ và học hỏi từ những kỷ niệm.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_seven",
    "name_en": "Seven of Cups",
    "name_vn": "Seven of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Seven Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Seven of Cups đại diện cho sự quyết định và lựa chọn. Đây là giai đoạn bạn sẽ có nhiều lựa chọn, mỗi một lựa chọn đều đem lại kết quả khác nhau. Tuy nhiên, phần lớn các lựa chọn đều bị giới hạn thời gian. Nếu bạn đắn đo các lựa chọn sẽ không còn hiệu lực. Thời gian này bạn cũng có thể nhận được nhiều lời khuyên từ những người khác nhau, bạn không nhất thiết phải tiếp thu tất cả chúng, hãy chọn lựa điều hợp lý nhất.",
    "journey_story": "Seven of Cups biểu thị sự tưởng tượng, những giấc mơ và sự bối rối trước nhiều lựa chọn. Lá bài nhắc nhở bạn cần tỉnh táo và chọn lựa khôn ngoan.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_eight",
    "name_en": "Eight of Cups",
    "name_vn": "Eight of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Eight of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Eight of Cups thường mang nghĩa tiêu cực nhiều hơn. Giai đoạn này, bạn buộc phải rời khỏi một mối quan hệ, rút khỏi một dự án, chấm dứt một tình yêu hoặc một tình bạn. Cũng tại thời điểm này, bạn thường xuyên căng thẳng và mệt mỏi. Chỉ khi rũ bỏ những thứ đang gây cản trở, bạn mới có thể tiến về phía trước. Điều đáng mừng là bạn nhận thức được tình huống hiện tại và nỗ lực để có cuộc sống như mơ ước.",
    "journey_story": "Eight of Cups biểu thị sự buông bỏ, rời xa những gì không còn phục vụ bạn nữa và tìm kiếm ý nghĩa mới. Lá bài khuyến khích bạn dũng cảm để theo đuổi điều tốt đẹp hơn.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_nine",
    "name_en": "Nine of Cups",
    "name_vn": "Nine of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Nine Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Nine of Cups là kết quả của sự buồn chán, bạn nhận ra những gì mình từng mong muốn và kiếm tìm không mang lại cảm giác thỏa mãn như tưởng tượng. Vùng đất cằn cỗi mà người đàn ông đi qua thể hiện những thách thức trong cuộc đời. Nó cũng cho thấy sự tách biệt bản thân khỏi những người khác để tự phát triển và hoàn thiện bản thân. Lá bài Eight of Cups xuôi biểu thị thời gian của sự chuyển đổi, sau khi quá mệt mỏi sau hành trình dài, người ta sẽ chiêm nghiệm ra những triết lý sống mới.",
    "journey_story": "Nine of Cups là lá bài của sự thỏa mãn, thành công và hạnh phúc. Lá bài nhắc nhở bạn tận hưởng những thành quả mà bạn đã làm việc chăm chỉ để đạt được.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_ten",
    "name_en": "Ten of Cups",
    "name_vn": "Ten of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ten Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ten of Cups mang đến thông điệp rằng giấc mơ sẽ thành sự thật. Nếu bạn đã phải trải qua giai đoạn khó khăn, vất vả để tìm kiếm điều mình ao ước thì giai đoạn này bạn có thể quay trở lại, tận hưởng cuộc sống hiện tại với tâm thế thoải mái nhất. Rất hiếm khi lá bài xuất hiện theo nghĩa tiêu cực, nhưng không phải không bao giờ có. Về tiêu cực, lá bài cảnh báo những thách thức, những điều bạn khao khát đã có được nhưng không khiến bạn hài lòng. Những điều bạn mong đợi không xảy ra theo kỳ vọng. Nên nhớ rằng khi bạn muốn có một điều gì đó bạn phải đáp ứng đủ yêu cầu để sở hữu nó.",
    "journey_story": "Ten of Cups đại diện cho hạnh phúc gia đình, tình yêu và sự hòa hợp. Lá bài này nhắc nhở bạn về giá trị của gia đình và sự kết nối với người thân yêu.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_page",
    "name_en": "Page of Cups",
    "name_vn": "Page of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Page Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Page of Cups đại diện cho sự nhạy cảm, giai đoạn này bạn đang sống trong sự mơ mộng quá mức và nhạy cảm với các vấn đề mà trước kia vẫn coi là bình thường. Đây là lá bài trung tính, xấu hay tốt phụ thuộc vào bối cảnh xảy ra. Điều chắc chắn là bạn có thể cáu gắt khó chịu với ai đó hoặc bạn cảm thấy rằng ai đó có thái độ không mấy thiện cảm với mình. Sự mơ mộng này không chỉ trong tình yêu mà còn cả công việc lẫn các mối quan hệ khác. Điều này tốt cho việc nuôi dưỡng cảm xúc lạc quan và yêu đời. Nhưng nhiều khi, điều này gây mất thời gian và khiến bạn thất vọng nếu hiện thực không diễn ra như những gì bạn mơ mộng. Đôi khi bạn hành xử khá trẻ con hơn độ tuổi của mình, bạn nhạy cảm và tiêu cực khi các rắc rối xảy ra.",
    "journey_story": "Page of Cups biểu thị sự sáng tạo, trực giác và cảm xúc mới. Lá bài nhắc nhở bạn mở lòng để đón nhận những cảm hứng bất ngờ.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_knight",
    "name_en": "Knight of Cups",
    "name_vn": "Knight of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Knight Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Knight of Cups là một lá bài tốt và mang tính lạc quan khi xuất hiện trong một giải bài. Nó thường đại diện cho sự khôn ngoan đến từ những giấc mơ của bạn và giúp bạn vượt qua những trở ngại của cuộc sống. Lá bài này thường có nghĩa rằng những tin tốt (đặc biệt trong thế giới nội tâm bạn) dường như sắp đến với bạn. Nó cũng có thể hàm ý đến một lời cầu hôn / cuộc hôn nhân nếu bạn đang trong một mối quan hệ.",
    "journey_story": "Knight of Cups biểu thị sự lãng mạn, lòng nhiệt tình và khát vọng cảm xúc. Lá bài nhắc nhở bạn theo đuổi những gì khiến trái tim bạn rung động.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_queen",
    "name_en": "Queen of Cups",
    "name_vn": "Nữ Hoàng Cốc",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Queen Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Queen of Cups đại diện cho sự nhạy cảm, từ bi và lòng nhân ái của một người phụ nữ từng trải qua những tổn thương sâu sắc. Người này có thể là mẹ, cấp trên, đồng nghiệp, người yêu hoặc chính bản thân bạn nếu bạn là nữ. Lá bài cho rằng giai đoạn này bạn đang cảm thấy cô đơn và khó thích nghi với môi trường xung quanh. Bạn đang có xu hướng đóng cửa trái tim và không muốn giao tiếp với mọi người. Những tổn thương từ quá khứ khiến bạn khép mình nhưng lại mang đến cho bạn sự nhạy cảm, chín chắn và cẩn trọng từng lời ăn tiếng nói. Bạn là người cầu toàn nên luôn đặt ra những mục tiêu lớn trong công việc và bạn chăm chỉ để đạt được nó. Về tình yêu, nếu muốn bắt đầu một mối quan hệ bạn nên có sự tìm hiểu kỹ càng về đối phương để tránh vỡ mộng. Bạn luôn nhạy cảm với nhiều vấn đề trong chuyện tình cảm, điều này có thể gây ra những sứt mẻ về mặt cảm xúc. Lá bài Queen of Cups khuyên rằng nên thoải mái hơn, mở lòng với những mối quan hệ sẽ xoa dịu vết thương cũ. Tuổi còn trẻ nên bạn hãy tận dụng thời gian của mình để được tận hưởng dư vị ngọt ngào trong tình huống. Nếu bạn muốn biết người yêu hiện tại có là người bạn lý tưởng của mình không thì hãy nhìn những gì người đó làm chứ không phải những câu nói mật ngọt sáo rỗng. Về công việc, bạn là người có khả năng làm việc độc lập, bạn luôn nỗ lực hết mình vì mục tiêu của bản thân. Tuy nhiên, bạn lại không thích những công việc cố định, an nhàn. Bạn khao khát được làm việc trong môi trường được cống hiến và sáng tạo. Nên đừng đắn đo nếu bạn đang muốn nhảy việc. Lá bài còn cảnh báo những rắc rối có thể đến do cách xử lý công việc thiếu sự thận trọng. Mọi quyết định đưa ra trong giai đoạn này cần một sự dứt khoát, tránh vòng vo quanh quẩn để gây ra hậu quả. Về tiền bạc, nếu bạn đang gặp rắc rối về tài chính, bạn sẽ nhận được sự trợ giúp của những người thân quen. Hãy đón nhận sự giúp đỡ bằng thái độ biết ơn, đừng lẩn tránh sự quan tâm và giúp đỡ của người khác. Hãy mở lòng để tạo dựng những mối quan hệ, bạn sẽ được hỗ trợ về mặt tiền bạc từ những mối quan hệ này khi gặp khó khăn. Ngoài ra, Queen of Cups cảnh báo sự ăn tiêu theo cảm tính sẽ khiến bạn sớm cháy túi. Hãy tiêu tiền và đầu tư một cách thông thái, tránh giữ quá nhiều tiền mặt bên người. Về sức khỏe, lá bài cảnh báo những căn bệnh cũ trong quá khứ có thể quay lại. Bạn nên điều trị triệt để, tránh gây tai họa về sau. Lá bài còn ám chỉ những ám ảnh của sự đổ vỡ tình cảm trong quá khứ khiến bạn dằn vặt và luôn buồn rầu. Hãy tham gia nhiều hoạt động tập thể để được thư giãn, nếu tình trạng kéo dài bạn nên đi gặp bác sĩ tâm lý để được tư vấn.",
    "journey_story": "Queen of Cups đại diện cho sự đồng cảm, trực giác và tình yêu vô điều kiện. Lá bài nhắc nhở bạn lắng nghe trái tim mình và cảm nhận sâu sắc những cảm xúc xung quanh.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_cups_king",
    "name_en": "King of Cups",
    "name_vn": "King of Cups",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/King Of Cups.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài King of Cups đại diện cho sự trưởng thành về mặt cảm xúc, đây là giai đoạn những cá tính sẽ được thể hiện rõ nét nhất. Những cảm xúc trong bạn cũng sẽ trưởng thành và dần đạt được trạng thái cân bằng. Lá bài tượng trưng cho sự cân bằng giữ trí tuệ và cảm xúc, trực giác của bạn trở nên nhạy bén và chính xác hơn bao giờ hết. Lá bài đại diện cho sự trưởng thành trong tính cách và tình cảm, sự trung thành và tận tụy.",
    "journey_story": "King of Cups đại diện cho sự cân bằng cảm xúc, lòng từ bi và trí tuệ. Lá bài nhắc nhở bạn duy trì sự ổn định và sử dụng cảm xúc một cách khôn ngoan.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_ace",
    "name_en": "Ace of Swords",
    "name_vn": "Ace of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ace Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ace of Swords đại diện cho sự đột phá, khi lá bài xuất hiện bạn sẽ phải trải qua một một trải nghiệm lớn trong đời. Lá bài nói rằng quan niệm và suy nghĩ của bạn sẽ có sự thay đổi, bạn sẽ nhìn nhận mọi việc ở một góc độ hoàn toàn mới. Đây là lá bài trung tính, việc xấu hay tốt phụ thuộc vào mục đích sử dụng của bạn.",
    "journey_story": "Ace of Swords biểu thị sự bắt đầu của trí tuệ, sự rõ ràng và khả năng phân tích. Lá bài nhắc nhở bạn về sức mạnh của sự thật và logic.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_two",
    "name_en": "Two of Swords",
    "name_vn": "Two of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Two Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Two of Swords xuất hiện khi bạn gặp bế tắc và buộc phải đưa ra lựa chọn. Đây là giai đoạn bạn phải đối diện với xung đột và đối thủ cạnh tranh. Lá bài cảnh báo bạn phải kiên trì và không để tâm trí bị lung lay. Bạn nên lựa chọn theo số đông và làm tốt bổn phận, trách nhiệm của mình. Lá bài cũng khuyên bạn nên giữ mối quan hệ tình cảm ở trạng thái cân bằng và chia sẻ các vấn đề với người ấy.",
    "journey_story": "Two of Swords biểu thị sự đấu tranh nội tâm và những quyết định khó khăn. Lá bài nhắc nhở bạn cần cân nhắc kỹ lưỡng để đưa ra lựa chọn đúng đắn.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_three",
    "name_en": "Three of Swords",
    "name_vn": "Three of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Three Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Three of Swords đại diện cho nỗi buồn và mất mát về mặt cảm xúc. Nó cảnh báo rằng giai đoạn khó khăn trong cuộc đời bạn chính thức bắt đầu, với những nỗi đau và mất mát ảnh hưởng nghiêm trọng tới hành động của bạn. Lá bài thường đại diện cho sự phản bội trong công việc hoặc tình yêu, và dự đoán những sứt mẻ về chuyện tình cảm. Tuy nhiên, nó cũng có thể đại diện cho việc rời bỏ một thứ không còn mang lại hạnh phúc cho bạn, đây vừa là mất mát nhưng cũng là cơ hội để bắt đầu lại.",
    "journey_story": "Three of Swords biểu thị nỗi đau, sự tổn thương và mất mát. Lá bài nhắc nhở bạn rằng dù đau khổ, bạn vẫn có thể học hỏi và trưởng thành từ những trải nghiệm đó.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_four",
    "name_en": "Four of Swords",
    "name_vn": "Four of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Four Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Four of Swords là lá bài của sự tĩnh lặng. Đây là giai đoạn bạn sẽ đi chậm lại và nghiền ngẫm những việc đã làm. Một số kế hoạch trong cuộc sống của bạn dù muốn hay không cũng bị dừng lại. Lá bài dự đoán bạn đang thực hiện sẽ không thành hiện thực hoặc không mang lại kết quả gì. Bạn sẽ trải qua thời gian nghỉ ngơi và phục hồi, dừng lại và chăm sóc bản thân cùng những người xung quanh. Đây là giai đoạn để nghỉ ngơi và sạc đầy năng lượng để đối mặt với các thử thách tiếp theo.",
    "journey_story": "Four of Swords biểu thị sự nghỉ ngơi, hồi phục và suy ngẫm. Lá bài nhắc nhở bạn cần dành thời gian để tái tạo năng lượng và chuẩn bị cho những thử thách tiếp theo.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_five",
    "name_en": "Five of Swords",
    "name_vn": "Five of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Five Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Five of Swords dự đoán sự mất mát. Bạn sẽ bị mất một thứ gì đó bởi sự bất cẩn. Đây là giai đoạn bạn phải đấu tranh để giành lại những thứ thuộc về mình. Tuy nhiên, lá bài cho rằng bạn sẽ phải nhận thất bại dù đã rất cố gắng. Lá bài cảnh báo vòng tròn bạn bè, bạn có thể mất tất cả từ tiền bạc, địa vị, danh tiếng chỉ vì những người này. Mặt khác, đây là giai đoạn của sự cạnh tranh khốc liệt. Five of Swords thường mang nghĩa tiêu cực, bạn sẽ thua cuộc và chấp nhận sự mất mát. Tuy nhiên, điều an ủi là những thứ đối thủ nhận được không thật sự có ý nghĩa.",
    "journey_story": "Five of Swords biểu thị sự xung đột, mất mát và hậu quả của chiến thắng không công bằng. Lá bài nhắc nhở bạn cần cân nhắc về cách hành xử và quyết định của mình.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_six",
    "name_en": "Six of Swords",
    "name_vn": "Six of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Six Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Six of Swords đại diện cho sự di chuyển, tiến bộ và thay đổi trong cuộc sống. Nó có thể ám chỉ những chuyến đi xa nhà, xuất ngoại hoặc di chuyển trong lĩnh vực công việc hoặc mối quan hệ. Tuy nhiên, lá bài cũng có thể cho thấy sự thất bại, chán nản và ý nghĩ tiêu cực nếu tham vọng đặt nhầm chỗ. Để thành công, bạn cần quan tâm nhiều hơn tới những người xung quanh, kiềm chế tham vọng bản thân và chấp nhận sự thật.",
    "journey_story": "Six of Swords biểu thị sự chuyển đổi, vượt qua khó khăn và hướng tới một tương lai tốt đẹp hơn. Lá bài nhắc nhở bạn cần chấp nhận sự thay đổi để đạt được bình yên.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_seven",
    "name_en": "Seven of Swords",
    "name_vn": "Seven of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Seven of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Seven of Swords thông báo sự phản bội và lừa dối. Bạn sẽ bị những người xung quanh phản bội và lừa dối, họ không trung thành và sẵn sàng ném bạn xuống khi hết giá trị. Tuy nhiên, đây sẽ là bài học quý giá cho sau này. Lá bài cũng cảnh báo sự gian dối trong kinh doanh và sự chơi xấu của đồng nghiệp. Bạn nên xác định rõ mình đang theo đuổi điều gì và đam mê cuối cùng là gì để không mất thời gian.",
    "journey_story": "Seven of Swords biểu thị sự mưu mẹo, trốn tránh và hành động lén lút. Lá bài nhắc nhở bạn cần trung thực và cẩn thận để tránh hậu quả không mong muốn.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_eight",
    "name_en": "Eight of Swords",
    "name_vn": "Eight of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Eight Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Eight of Swords là lá bài của sự vướng mắc. Giai đoạn này, bạn sẽ luôn cảm thấy mình bị mắc kẹt và không thể nào thoát ra. Các vấn đề rắc rối liên tục đến và bạn không biết phải làm thế nào để giải quyết chúng. Trong một số tình huống, bạn còn không nhận thức được là mình đang bị mắc kẹt. Lá bài đại diện cho sự hạn chế và ràng buộc, bạn luôn luôn mọi việc phát triển theo chủ nghĩa hoàn hảo và không bao giờ muốn ai đó thất vọng về mình. Bạn đang bị ràng buộc về tinh thần, bạn cảm thấy mình có trách nhiệm với mọi thứ xung quanh. Mặt khác, nó đại diện cho sự chỉ trích, bạn đang quá nhạy cảm và lo sợ phản ứng của những người xung quanh. Lá bài cho rằng bạn đang thiếu tự tin vào chính bản thân mình, đôi khi kẻ thù lớn nhất là chính bản thân bạn.",
    "journey_story": "Eight of Swords biểu thị sự sợ hãi, hạn chế và cảm giác bất lực. Lá bài nhắc nhở bạn rằng nhiều rào cản là do tự tạo ra và có thể vượt qua.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_nine",
    "name_en": "Nine of Swords",
    "name_vn": "Nine of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Nine Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Nine of Swords thể hiện sự lo lắng và đau khổ về mặt cảm xúc. Bạn sẽ trải qua một thời kỳ khó khăn và muộn phiền trong thời gian tới. Lá bài ám chỉ sự đổ vỡ của những mối quan hệ hoặc những kế hoạch gần như sắp hoàn thành nhưng lại sụp đổ đột ngột. Bạn bị rơi vào trạng thái hỗn loạn và không tin được những điều tồi tệ này lại xảy đến với mình. Tuy nhiên, lá bài cho rằng vẫn còn những tia hy vọng cho tình huống xấu nhất. Khi mọi thứ chưa kết thúc hoàn toàn, bạn vẫn còn cơ hội cứu vãn tình hình.",
    "journey_story": "Nine of Swords biểu thị nỗi lo lắng, ám ảnh và cảm giác tội lỗi. Lá bài nhắc nhở bạn cần đối mặt với nỗi sợ hãi và tìm cách chữa lành tinh thần.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_ten",
    "name_en": "Ten of Swords",
    "name_vn": "Ten of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ten Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ten of Swords ám chỉ sự sụp đổ, công việc, sự nghiệp, mối quan hệ sẽ bị sụp đổ tại thời điểm này. Lá bài cảnh báo sự nghèo đói, nợ nần và cô đơn. Một số trường hợp, lá bài đại diện cho sự yếu ớt về thể chất, bạn sẽ gặp những vấn đề liên quan tới sức khỏe. Trầm cảm hoặc thần kinh không ổn định có thể là căn bệnh sẽ đeo bám bạn. Tuy nhiên, ngay cả trong tình huống xấu nhất bạn vẫn được quyền hy vọng vào một tương lai tốt đẹp hơn.",
    "journey_story": "Ten of Swords biểu thị sự kết thúc đau đớn, phản bội và sự sụp đổ. Lá bài nhắc nhở bạn rằng sau sự sụp đổ là cơ hội để tái sinh và bắt đầu lại.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_page",
    "name_en": "Page of Swords",
    "name_vn": "Page of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Page Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Page of Swords đại diện cho sự tò mò và hiếu kỳ. Khi lá bài xuất hiện, bạn hoặc ai đó xung quanh bạn đang có xu hướng thích buôn chuyện, bàn tán về những thứ mình đã trải qua. Mặt khác, lá bài cảnh báo rằng những người xung quanh có thể tạo ra những rắc rối cho bạn bởi sự hiếu kỳ của họ. Lá bài này cũng có thể đại diện cho sự thông tin và kiến thức mới, giúp bạn có thể giải quyết các vấn đề và thách thức trong cuộc sống.",
    "journey_story": "Page of Swords biểu thị sự tò mò, trí thông minh và khao khát tìm hiểu. Lá bà i nhắc nhở bạn luôn cảnh giác và sẵn sàng học hỏi những điều mới.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_knight",
    "name_en": "Knight of Swords",
    "name_vn": "Knight of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Knight Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Knight of Swords đại diện cho sự hủy diệt và phá hủy sự yên bình hiện tại. Nó cảnh báo rằng bạn có thể gặp rắc rối bởi những người này. Ngoài ra, kẻ gây rối ở đây có thể chính là bản thân bạn. Lá bài này cũng đại diện cho người hiệp sĩ hung hăng, anh ta làm tất cả những gì mình muốn và không lắng nghe người khác. Anh ta không phải kiểu người sẽ kìm hãm sự nóng vội của mình.",
    "journey_story": "Knight of Swords biểu thị sự hành động nhanh chóng, táo bạo và khả năng vượt qua thử thách. Lá bài nhắc nhở bạn cần có kế hoạch trước khi hành động để tránh rủi ro.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_queen",
    "name_en": "Queen of Swords",
    "name_vn": "Queen of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Queen Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Queen of Swords đại diện cho người phụ nữ sáng suốt và thông tuệ. Lá bài ám chỉ rằng sẽ có một người phụ nữ can dự vào cuộc đời của bạn, người này đang có ý định gây rối. Họ muốn can thiệp vào công việc kinh doanh của bạn, cảnh báo sự ảnh hưởng của người này đến cuộc đời của bạn. Lá bài thể hiện tầm quan trọng của việc đưa ra phán xét mà dựa vào lý trí chứ không phải cảm xúc, đôi khi lá bài đại diện cho sự vô cảm. Mặt khác, đây có thể là khoảng thời gian bạn sẽ cảm thấy cô đơn và cảm thấy mất niềm tin vào mọi thứ xung quanh. Mặc dù là lá bài tiêu cực nhưng cũng xuất hiện dưới dạng tích cực trong một số tình huống. Bạn nên tự mình vượt qua những thử thách của cuộc sống, không nên dựa dẫm vào người khác.",
    "journey_story": "Queen of Swords đại diện cho sự thông minh, tính độc lập và khả năng đưa ra quyết định rõ ràng. Lá bài nhắc nhở bạn sử dụng trí tuệ và lý trí để giải quyết vấn đề.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_swords_king",
    "name_en": "King of Swords",
    "name_vn": "King of Swords",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/King Of Swords.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài King of Swords đại diện cho vị vua thông minh dùng sự thông tuệ của mình để chiến thắng mọi kẻ thù. Lá bài xuất hiện ám chỉ bạn sẽ gặp một người đàn ông trong tương lai gần, người này sẽ giúp đỡ hoặc cản trở sự phát triển của bạn. Ý nghĩa lá bài King of Swords đại diện cho kỷ luật, bạn đang bị ai đó đánh giá một cách khắt khe. Người này theo dõi những bước đi của bạn, nhân vật này thường là một người đàn ông, cụ thể là bố bạn, thầy giáo, cấp trên hoặc những người thân yêu của bạn. Đôi khi lá bài xuất hiện như một lời nhắc nhở rằng bạn nên sống thực tế hơn, tách mình ra khỏi cảm xúc cá nhân. Sử dụng toàn bộ lý trí và sự thông minh của bạn để biến những tình huống bất lợi thành lợi thế.",
    "journey_story": "King of Swords biểu thị sự lãnh đạo, trí tuệ và khả năng đưa ra quyết định công bằng. Lá bài nhắc nhở bạn sử dụng lý trí và công lý để giải quyết vấn đề.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_ace",
    "name_en": "Ace of Pentacles",
    "name_vn": "Ace of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ace Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Ace of Pentacles là lá bài của sự khởi đầu, ám chỉ một thành công mới đang đến rất gần. Lá bài thường mang nghĩa tích cực, dường như mọi thứ đang đứng về phía bạn. Giai đoạn này, bạn sẽ nhận được phần thưởng cho sự cố gắng và tận tụy của mình. Lá bài còn thông báo một chu kỳ mới đang được bắt đầu, những cơ hội có thể sẽ xuất hiện.",
    "journey_story": "Ace of Pentacles biểu thị sự khởi đầu của cơ hội tài chính, thành công vật chất và sự thịnh vượng. Lá bài nhắc nhở bạn nắm bắt cơ hội để phát triển.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_two",
    "name_en": "Two of Pentacles",
    "name_vn": "Two of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Two Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Two of Pentacles đại diện cho sự quản lý, lá bài xuất hiện đánh dấu giai đoạn bạn cần cân bằng lại mọi khía cạnh trong cuộc sống của mình. Mọi vấn đề về tài chính trong giai đoạn này cần được kiểm soát gắt gao. Đây không phải lá bài tích cực nhưng cũng không phải là lá bài quá xấu. Lá bài nhắc nhở rằng mọi vấn đề về tài chính cần được kiểm soát, nếu bạn chưa có sự sắp xếp trong thu chi thì giai đoạn này cần sắp xếp lại mọi thứ. Nếu không phải vấn đề về tiền bạc thì lá bài nhắc nhở rằng bạn đang phung phí thời gian của mình cho những thứ không có giá trị. Mặc dù mang nhiều nghĩa tiêu cực nhưng Two Of Pentacles khẳng định rằng những rắc rối về tài chính sẽ không diễn ra quá lâu. Đây là thời kỳ bạn nên suy nghĩ và quản lý mọi việc để tạo ra một sự ổn định lâu dài.",
    "journey_story": "Two of Pentacles đại diện cho sự cân bằng giữa các trách nhiệm và khả năng thích nghi với hoàn cảnh thay đổi. Lá bài nhắc nhở bạn giữ vững sự linh hoạt.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_three",
    "name_en": "Three of Pentacles",
    "name_vn": "Three of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Three Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Three of Pentacles đánh dấu khoảng thời gian bạn đang nỗ lực phát triển bản thân cho tương lai. Trong thời điểm này bạn có thể tiếp tục học lên cao hoặc tiếp tục rèn luyện các kỹ năng nghề nghiệp. Vì sở hữu những tài năng thiên bẩm nên bạn sẽ dễ dàng tiếp thu và chọn lọc được những kiến thức bổ ích. Lá bài này cho thấy những sự cố gắng, nỗ lực của bạn đang đem lại những tín hiệu tích cực. Lá bài đánh dấu hành trình của những nỗ lực, những kết quả hiện tại không phải là cuối cùng. Do vậy, bạn không được ngừng cố gắng và trau dồi bản thân. Bạn đang sở hữu một tinh thần chiến đấu tuyệt vời, điều này là tốt để thực hiện những ước mơ. Tuy nhiên, lá bài cảnh báo rằng những người càng sở hữu nhiều tài năng thiên bẩm thì càng dễ trở nên kiêu ngạo, bạn có thể tài năng trong lĩnh vực này nhưng điều đó không có nghĩa rằng không ai có thể giỏi hơn bạn. Ngoài ra, bạn có thể trở thành chủ đề của những ganh ghét, đố kỵ bởi những người không có tài năng bẩm sinh như bạn.",
    "journey_story": "Three of Pentacles biểu thị sự hợp tác, kỹ năng và công nhận. Lá bài nhắc nh ở bạn làm việc cùng người khác để đạt được mục tiêu chung.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_four",
    "name_en": "Four of Pentacles",
    "name_vn": "Four of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Four Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Four of Pentacles đại diện cho sự sở hữu, tích trữ và cố chấp. Nó ám chỉ rằng bạn đang cố gắng giữ một thứ gì đó mà không muốn chia sẻ nó với bất kỳ ai, dù nó có giá trị sử dụng hay không. Lá bài này cũng thể hiện những ám ảnh của bạn, bạn đang có xu hướng tự lừa dối bản thân và làm phiền người khác. Đôi khi sự cố chấp có thể mang lại kết quả tốt nếu bạn biết áp dụng nó vào việc chinh phục những mục tiêu, nhưng những sự cố chấp, ngang bướng sẽ khiến bạn thua thiệt trong đa số tình huống.",
    "journey_story": "Four of Pentacles biểu thị sự giữ gìn, ổn định tài chính và nỗi sợ mất mát. Lá bài nhắc nhở bạn cẩn thận với cách quản lý tài sản.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_five",
    "name_en": "Five of Pentacles",
    "name_vn": "Five of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Five of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Five of Pentacles ám chỉ sự nghèo nàn trong bài đọc về tài chính. Lá bài ám chỉ sự bất an và bối rối liên quan tới việc kinh doanh và tình hình tài chính của bạn. Đôi khi lá bài dự báo một sự mất mát sắp xảy ra trong thời gian tới, hãy chuẩn bị tâm lý. Ý nghĩa lá bài Five of Pentacles không phải là lá bài mang nghĩa tích cực. Lá bài ẩn chứa sự mất mát. Giai đoạn này công việc, tiền bạc của bạn có thể rơi vào trạng thái cảnh báo. Những vấn đề liên quan tới tài chính sẽ khiến bạn mệt mỏi và căng thẳng. Lá bài còn dự đoán sự cô đơn được đẩy đến đỉnh điểm, bạn không tìm được sự an ủi ở bất kỳ thứ gì. Bệnh tật, nghèo đói, thiếu thốn tình cảm đều có thể đến tại thời điểm này.",
    "journey_story": "Five of Pentacles biểu thị sự thiếu thốn, khó khăn tài chính và cảm giác bị cô lập. Lá bài nhắc nhở bạn tìm kiếm sự giúp đỡ và giữ vững niềm tin.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_six",
    "name_en": "Six of Pentacles",
    "name_vn": "Six of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Six Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Six of Pentacles thể hiện sự chia sẻ, đại diện cho sự cho hoặc nhận hỗ trợ tài chính. Nó cũng có thể đại diện cho sự hào phóng trong tình yêu và cảm xúc. Ý nghĩa lá bài này ám chỉ bạn sẽ nhận được sự giúp đỡ nếu đang gặp khó khăn về tài chính. Sự hỗ trợ này có thể đến từ ngân hàng hoặc những người thân yêu trong cuộc sống. Trường hợp, bạn là người ổn định về mặt tài chính thì bạn chính là người đi hỗ trợ. Một số trường hợp khác, lá bài nói rằng bạn nên chủ động trong mọi tình huống để không đánh mất cơ hội. Đôi khi, lá bài lại dự đoán những bất ổn về tài chính khiến bạn khốn đốn. Về tình yêu, nếu bạn vẫn đang độc thân thì giai đoạn tới sẽ có khá nhiều lựa chọn dành cho bạn, không nên quá hấp tấp. Tuy nhiên, nếu bạn đang trong một mối quan hệ thì đây không phải giai đoạn thích hợp, bạn và người ấy sẽ nảy sinh những tranh cãi. Cả bạn và người ấy đều cảm thấy mất cân bằng và thấy mình hy sinh quá nhiều cho đối phương, tình trạng này kéo dài khiến cả hai cảm thấy mệt mỏi. Lá bài Six of Pentacles trong tình yêu khuyên rằng cả hai nên bình tĩnh nhìn nhận lại tình cảm hiện tại và cùng nhau tìm cách giải quyết trước khi quá muộn. Về công việc, Six of Pentacles thông báo sự ổn định về công việc trong thời gian tới. Nếu bạn đang loay hoay và chật vật với công việc hiện tại thì cũng không cần lo lắng, giai đoạn này sẽ trôi qua rất nhanh. Tại thời điểm này, bạn sẽ nhận được sự giúp đỡ từ đồng nghiệp hoặc cấp trên. Ngoài ra, đây là giai đoạn thích hợp để điều chỉnh những sai lầm trong công việc do quá khứ gây ra. Tuy khá thuận lợi nhưng không nên mở rộng kinh doanh hay đầu tư mạo hiểm. Về tiền bạc, lá bài Six of Pentacles mang ý nghĩa cảnh báo sự tham lam của bạn đối với vấn đề liên quan tới tiền bạc. Sự mạo hiểm kiếm lợi từ khó khăn của người khác sẽ khiến bạn vướng vào rắc rối pháp lý. Lá bài khuyên rằng bạn nên biết hài lòng với hoàn cảnh hiện tại. Bên cạnh đó, giai đoạn này bạn còn nhận được sự giúp đỡ từ phía những người thân yêu về tài chính.",
    "journey_story": "Six of Pentacles biểu thị sự cân bằng giữa cho và nhận, lòng hào phóng và sự hỗ trợ. Lá bài nhắc nhở bạn về giá trị của việc giúp đỡ người khác và sự công bằng.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_seven",
    "name_en": "Seven of Pentacles",
    "name_vn": "Seven of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Seven Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Seven of Pentacles thể hiện sự tăng trưởng và phát triển. Đây là giai đoạn của sự gia tăng và phát triển, bạn có thể mong đợi sự gia tăng về tài sản, cổ phiếu và những may mắn về tiền bạc. Lá bài cũng cho rằng bạn nên kiên trì và vững tin vào những gì mình làm.",
    "journey_story": "Seven of Pentacles đại diện cho sự kiên nhẫn, đầu tư dài hạn và chờ đợi kết quả. Lá bài nhắc nhở bạn đánh giá lại những nỗ lực của mình và kiên trì hướng tới mục tiêu.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_eight",
    "name_en": "Eight of Pentacles",
    "name_vn": "Eight of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Eight Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Eight of Pentacles đại diện cho sự đam mê và làm chủ bản thân. Với sự xuất hiện của lá bài này, bạn sẽ trở thành người làm chủ mọi vấn đề. Ngoài ra, bạn có thể trở thành một chuyên gia trong lĩnh vực nào đó trong thời gian tới. Những gì bạn làm trước đây chỉ vì đam mê thì bây giờ có thể thành công cụ kiếm tiền. Ý nghĩa lá bài Eight of Pentacles ám chỉ rằng những trò tiêu khiển của bạn đang trở thành sự nghiệp của bạn. Bạn sẽ rất bất ngờ khi những thứ mình làm vì đam mê và sở thích lại có thể trở thành một nguồn khai thác tạo ra giá trị kinh tế và nuôi sống chính bạn. Xuất hiện ở dạng tiêu cực, lá bài cảnh báo bạn đang có cách làm việc độc tài. Bạn khó chịu khi bị điều khiển. Bạn đang cho rằng mình là một chuyên gia và không muốn bị bất cứ ai chỉ đạo. Nhưng nên nhớ rằng bạn là bậc thầy trong một lĩnh vực không có nghĩa bạn giỏi tất cả mọi thứ.",
    "journey_story": "Eight of Pentacles biểu thị sự chăm chỉ, trau dồi kỹ năng và cống hiến cho công việc. Lá bài nhắc nhở bạn về giá trị của việc nỗ lực và cam kết để đạt được sự thành thạo.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_nine",
    "name_en": "Nine of Pentacles",
    "name_vn": "Nine of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Nine Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Nine of Pentacles thể hiện sự thanh thản. Khi lá bài xuất hiện, bạn sẽ dư giả về tài chính. Lá bài đánh dấu giai đoạn của những giao dịch. Đây là thời điểm bạn sẽ được tận hưởng thành quả lao động của mình. Tổng quan về lá bài Nine of Pentacles, lá bài thường tập trung vào tài chính và những thứ liên quan tới vật chất. Tuy nhiên, lá bài cảnh báo rằng bạn có thể có được rất nhiều thứ nhưng chúng không đủ để khiến bạn thỏa mãn.",
    "journey_story": "Nine of Pentacles đại diện cho sự độc lập, tự hào và thành tựu cá nhân. Lá bài nhắc nhở bạn tận hưởng kết quả của những nỗ lực lâu dài.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_ten",
    "name_en": "Ten of Pentacles",
    "name_vn": "Ten of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Ten Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Ten of Pentacles đại diện cho sự đa dạng và phong phú trong cuộc sống. Nó ám chỉ sự gia tăng về mặt tài chính và những điều tốt đẹp đang tìm đến bạn. Lá bài này cũng khẳng định sự dồi dào về mặt tài chính và sự ổn định vững chắc trong công việc.",
    "journey_story": "Ten of Pentacles biểu thị sự giàu có, di sản và sự ổn định lâu dài. Lá bài nhắc nhở bạn về giá trị của việc xây dựng nền tảng bền vững cho tương lai.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_page",
    "name_en": "Page of Pentacles",
    "name_vn": "Page of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Page Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Page of Pentacles đại diện cho những ham muốn và tham vọng cháy bỏng. Nó thể hiện tầm quan trọng của gia đình và tài chính trong cuộc sống. Tuy nhiên, lá bài cũng cảnh báo về sự vay mượn quá mức và việc tập trung quá nhiều vào tiền bạc.",
    "journey_story": "Page of Pentacles đại diện cho sự tò mò, học hỏi và khám phá trong lĩnh vực vật chất hoặc tài chính. Lá bài nhắc nhở bạn mở lòng để học hỏi và phát triển.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_knight",
    "name_en": "Knight of Pentacles",
    "name_vn": "Knight of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Knight Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài Knight of Pentacles đại diện cho sự chăm chỉ và bền bỉ. Khi xuất hiện, nó khuyên bạn nên dành thời gian để làm việc một cách từ từ và cẩn thận, tránh vội vàng. Sự chăm chỉ tạo ra chất lượng, không phải số lượng. Lá bài này cũng cảnh báo việc bạn dành quá nhiều thời gian để suy nghĩ và lựa chọn, khiến cơ hội vụt mất. Về tình yêu, lá bài khuyên bạn nên suy nghĩ thật kỹ trước khi bắt đầu một mối quan hệ mới và duy trì một mối quan hệ bền vững bằng cách sẻ chia và cảm thông lẫn nhau. Về công việc, lá bài nhắc nhở bạn cần cẩn thận trước những mối quan hệ làm ăn và hợp tác, ổn định sự nghiệp hiện tại. Về tiền bạc, lá bài khuyên bạn nên tiết kiệm và không tiêu pha hoang phí.",
    "journey_story": "Knight of Pentacles biểu thị sự kiên nhẫn, trách nhiệm và sự nỗ lực để đạt được mục tiêu lâu dài. Lá bài nhắc nhở bạn tập trung vào công việc và kiên trì.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_queen",
    "name_en": "Queen of Pentacles",
    "name_vn": "Nữ hoàng Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/Queen Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Nữ hoàng Pentacles đại diện cho người phụ nữ thực tế, thông minh, hào phóng và thực tế. Cô là người luôn mong muốn những gì tốt nhất đến với chính mình và những người thân yêu. Lá bài thường mang tín hiệu tích cực trong buổi trải bài. Tuy nhiên, đôi khi, lá bài đại diện cho sự bảo thủ. Bạn không dám thoát ra khỏi vòng tròn an toàn do bản thân vẽ ra. Bạn tự thu hẹp tầm nhìn của mình lại. Trong khi thực tế thì bạn có thể đạt được nhiều hơn những gì kỳ vọng.",
    "journey_story": "Queen of Pentacles đại diện cho sự phong phú, thực tế và sự chăm sóc. Lá bài nhắc nhở bạn kết hợp sự ổn định vật chất với lòng yêu thương và sự quan tâm.",
    "upright_keywords": [],
    "reversed_keywords": []
  },
  {
    "id": "minor_pentacles_king",
    "name_en": "King of Pentacles",
    "name_vn": "King of Pentacles",
    "type": "Minor Arcana",
    "image": "/images/tarot_vn/King Of Pentacles.jpeg",
    "uprightMeaning": "",
    "reversedMeaning": "",
    "description": "Lá bài King of Pentacles định hướng kinh doanh và vấn đề liên quan tới tài chính. Khi lá bài này xuất hiện, tình hình tài chính của bạn sẽ có những khởi sắc. Lá bài có thể tượng trưng cho sự giàu có, thịnh vượng về mặt tiền bạc. Tổng quan về lá bài King of Pentacles, lá bài thường đại diện cho sự truyền thống. Bạn đang có xu hướng đi theo những định hướng từ gia đình. Bạn có thể khiến các thành viên trong gia đình tự hào vì bạn trong thời gian tới. Ngoài ra, lá bài thể hiện sự ổn định về vấn đề tiền bạc.",
    "journey_story": "King of Pentacles biểu thị sự thành công, ổn định và khả năng lãnh đạo trong lĩnh vực vật chất. Lá bài nhắc nhở bạn sử dụng tài nguyên củ a mình một cách khôn ngoan.",
    "upright_keywords": [],
    "reversed_keywords": []
  }
];
