export const tuviKnowledgeMini = `[DB TỬ VI CHÍNH TINH & LỤC SÁT]
- Tử Vi (Đế tinh, Nam Bắc Đẩu tinh, Dương Thổ): Chủ uy quyền, tài lộc, phúc đức; tượng trưng cho sự thông minh, trung hậu, nghiêm cẩn và oai phong. | Ý: An tại cung nào giáng phúc cung đó. Đi với Tả, Hữu, Xương, Khúc, Khôi, Việt thì uy quyền hiển hách, ví như quần thần khánh hội. Gặp Thất Sát ví như vua mang kiếm báu. Kỵ gặp Không Kiếp, Tuần Triệt làm giảm uy lực, bôn ba lao khổ.
- Liêm Trinh (Tù tinh, Đào hoa thứ 2, Bắc Đẩu tinh, Âm Hỏa): Chủ quan lộc, hình ngục; tượng trưng cho sự liêm khiết, thẳng thắn hoặc khắc nghiệt, tàn ác, dục vọng. | Ý: Đắc địa thủ Mệnh Thân có tính đào hoa. Hãm địa gặp Xương, Phù hoặc Sát tinh là Tù tinh, chủ kiện cáo, tù tội. Đi với Tham Lang ở Tỵ Hợi là phiêu lãng, tù tội.
- Thiên Đồng (Phúc tinh, Nam Đẩu tinh, Dương Thủy): Chủ phúc thọ, dung hòa, từ thiện; tính hay canh cải, thất thường. | Ý: Đắc địa chủ sự may mắn, vui vẻ. Hãm địa chủ tai họa, thị phi. Ở cung Tật ách hóa giải nhiều tai ương.
- Vũ Khúc (Tài tinh, Cương tinh, Bắc Đẩu tinh, Âm Kim): Chủ tài lộc, sự cương nghị, dũng mãnh. Hãm địa thì tham lam, ương ngạnh, phá tán. Tính chất như sao Cô, Quả. | Ý: Gặp Tham Lang đồng hành phát muộn (ngoài 30 tuổi). Miếu vượng gặp Sát tinh không đáng lo, nhưng hãm địa gặp Sát Kỵ Hình thì tai nạn, bần hàn.
- Thái Dương (Quý tinh, Nam Đẩu tinh, Dương Hỏa): Chủ quan lộc; biểu tượng mặt trời, người cha, người chồng; tượng trưng quang minh, bác ái, thông minh, nhân hậu. | Ý: Thuận lý khi sinh ban ngày. Kỵ Không Kiếp, Hình, Riêu, Kỵ làm giảm thọ, hỏng mắt. Hãm địa cần gặp Tuần Triệt để tăng vẻ sáng sủa. Đắc địa gặp Hóa Kỵ (mây ngũ sắc chầu) lại cực tốt.
- Thiên Cơ (Thiện tinh, Nam Đẩu tinh, Âm Mộc): Chủ huynh đệ, phúc thọ; tượng trưng trí tuệ, tinh thần, sự khéo léo, mưu cơ. | Ý: Gặp Xương Khúc, Khôi Việt, Tả Hữu, Song Hao đắc địa là hưởng phú quý, uy danh. Hãm địa gặp Sát Kỵ Hình thường tàn tật, phiêu bạt.
- Thiên Phủ (Tài tinh, Quyền tinh, Nam Đẩu tinh, Âm Thổ): Chủ tài lộc, quyền tước; tính nhân hậu, từ thiện, năng lực giải trừ bệnh tật. | Ý: Chế được tính hung ác của Kình, Đà, Hỏa, Linh. Rất kỵ Tuần, Triệt, Không Kiếp ví như kho tàng phá vỡ, hao tán.
- Thái Âm (Phú tinh, Bắc Đẩu tinh, Âm Thủy): Chủ điền trạch; biểu tượng mặt trăng, người mẹ, người vợ; tính khoan hòa, nhân hậu, tinh khiết. | Ý: Rất sáng sủa khi sinh ban đêm (đặc biệt từ mùng 10 đến rằm). Kỵ Không Kiếp, Riêu, Đà, Kỵ gây bệnh tật, đau mắt. Hãm địa cần Tuần, Triệt.
- Tham Lang (Hung tinh, Dâm tinh, Bắc Đẩu tinh, Âm Thủy (đới Mộc)): Chủ họa phúc, uy quyền; tượng trưng dục vọng, vật chất, sự xuất thế (khi hãm) hoặc tham lam, hung bạo. | Ý: Gặp Hỏa tinh, Linh tinh ở miếu địa (Tứ Mộ) cực kỳ phú quý (cách Tham Hỏa tương phùng). Gặp Đào Hồng hoặc hãm địa chủ dâm dật, họa tửu sắc.
- Cự Môn (Ám tinh, Bắc Đẩu tinh, Âm Thủy): Chủ ngôn ngữ, thị phi, nghi hoặc; tính vui vẻ nhưng hay gây khẩu thiệt, kiện cáo. | Ý: Đắc địa ở Tý Ngọ (Thạch trung ẩn ngọc) cần Hóa Lộc hoặc Tuần Triệt phá thạch. Hãm địa (Thìn Tuất) rất xấu, gây rắc rối, thị phi. Kỵ Hóa Kỵ (ngôn ngữ bất cẩn).
- Thiên Tướng (Quyền tinh, Dũng tinh, Nam Đẩu tinh, Dương Thủy): Chủ quan lộc, phúc thiện; tính đôn hậu, từ ái, can đảm, ưa thanh sắc. | Ý: Chế hóa được Sát tinh và tính ác của Liêm Trinh. Kỵ Tuần, Triệt và Thiên Hình (ví như tướng mất đầu) dễ dính tai họa khủng khiếp.
- Thiên Lương (Thọ tinh, Ấm tinh, Nam Đẩu tinh, Âm Mộc (đới Thổ)): Chủ phụ mẫu, phúc thọ; tính nhân hậu, giải trừ bệnh tật, tai họa. | Ý: Gặp Nhật ở Mão (Nhật xuất phù tang) cực quý. Ở Tỵ Hợi hãm địa tính phiêu bồng, dâm bôn.
- Thất Sát (Quyền tinh, Dũng tinh, Nam Đẩu tinh, Dương Kim (đới Hỏa)): Chủ sát phạt, uy quyền, oai phong lẫm liệt; biểu tượng sự quyết liệt. | Ý: Gặp Tử Vi thành gươm báu. Kỵ Không Kiếp, Kình Đà, Hỏa Linh dễ tổn thọ, mang tật. Hãm địa hung bạo, liều lĩnh.
- Phá Quân (Hao tinh, Hung tinh, Bắc Đẩu tinh, Âm Thủy): Chủ Phu thê, Tử tức, Nô bộc; biểu tượng sự phá hoại, tiêu hao, dũng mãnh, tàn bạo. | Ý: Tọa thủ ở đâu hao tán ở đó. Đi với Hao tinh thì càng phá. Hãm địa cực độc, kỵ Sát tinh. Đắc địa (Tý Ngọ) gặp Sát tinh lại lập đại công thời loạn.
- Kình Dương / Đà La (Sát tinh, Bắc Đẩu tinh, Kim đới Hỏa): Chủ sát phạt, hình thương, tàn tật, bướng bỉnh (Kình) và ám tật, nham hiểm (Đà). | Ý: Đắc địa Thìn Tuất Sửu Mùi chủ dũng mãnh, mưu lược. Kình Dương cư Ngọ thủ Mệnh (Mã đầu đới kiếm) uy quyền nhưng dễ tổn thọ. Hãm địa gây đâm chém, họa tù tội, ngã đau.
- Hỏa Tinh / Linh Tinh (Đoản thọ sát tinh, Nam Đẩu tinh, Hỏa đới Kim): Chủ sát phạt, thâm trầm, nóng nảy, thiêu đốt, giảm thọ. | Ý: Đắc địa (Dần Mão Thìn Tỵ Ngọ). Gặp Tham Lang, Vũ Khúc đắc địa thành tái thế anh hùng. Đi với Không Kiếp chủ chết đâm chém, sét đánh.
- Địa Không / Địa Kiếp (Sát tinh/Ác tinh, Hỏa): Ích kỷ, gian trá, bần tiện, gây phá hoại, tai nạn thê thảm, tán tài. | Ý: Tọa Tỵ Hợi đắc địa hoạnh phát hoạnh phá (bạo phát bạo tàn). Lâm Mệnh thủ Tứ sinh (như nửa chừng gãy cánh), chết non, cùng khổ. Cực kỳ kỵ với Tử, Phủ, Cự, Cơ, Đồng, Lương, Nhật, Nguyệt.
- Thiên Hình (Sát tinh / Hình tinh, Hỏa đới Kim): Sát phạt, binh nghiệp, đâm chém, mổ xẻ, pháp luật, uy dũng. | Ý: Miếu vượng (Dần Mão Dậu Tuất) hiển đạt võ nghiệp. Gặp Không Kiếp, Tuần Triệt thành tai nạn hình ngục, đâm chém đẫm máu. Chế được tính dâm của Đào Hồng.
`;
